cookie:
  expiry_days: 30
  key: sales_dashboard
  name: abcdef
credentials:
  usernames:
    adk1410:
      email: adk1410@gmail.com
      name: Atharv Khanvilkar
      password: $2b$12$WQ/z2YN7qvjXdLgPHUnBbeFFTBvnDy4UXJuzJnpZrPFgFRz.WzLnW
    admin:
      email: finanzeverse@gmail.com
      name: Admin
      password: $2b$12$qk4Z7Y6ReVetvIyZ5T/em.K2fQIrure4Lj38aSpIp6thjiLwf26ey
    poojanaik:
      email: poojanaik21@gmail.com
      name: Pooja Naik
      password: $2b$12$Zgw8uuEdO3fY2DQvnzMnZeimtGwALIh/vVJMBB/4Hfe5xzc6h3uZm
    tanvik:
      email: tanvikurhade811@gmail.com
      name: 'Tanvi '
      password: $2b$12$WmOVB3/NesWoaWCUb0ehmOne3qkfrgmv3a.pkM9rgc9SOh1d0Uu.a
    tanvikurhade:
      email: tanvikurhade811@gmail.com
      name: Tanvi
      password: $2b$12$HocW0DKHGoj1BtikegFHh.3ORe1/NsSz28VOsXqGoBr2b85Z/vMNW
    tanvikurhade_:
      email: kurhadetanvi@gmail.com
      name: Tanvi Kurhade
      password: $2b$12$xI7A7.VBXrmcydLx5zlqEeXP6hEENxlsvUVJF1NjhoBpPFNDByjZy
preauthorized:
  emails: []
